spring:
  application:
    name: eurekaserver
  security:
    basic:
      enable: true
    user:
      name: ${SPRING_SECURITY_USERNAME}
      password: ${SPRING_SECURITY_PW}

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

